### ISSUE TITLE
Synchronization issue

### ISSUE THREAD

**Issue by Nickfrm** [rigami/readme#8]
What about sync in this extension? 
I've added a new folder and a new bookmark via chrome. None of these has appeared in the Rigami bookmarks. Vice versa the ones created in the extension don't want to appear in the chrome bookmarks. It'll awesome if you'll create some sort of sync there to prevent such issues.

**Comment by danilkinkin** [comment]
Hello, sorry for late answer. Now i'm migrate to new extensions API (MV3).

I have some experience in this, but so far, due to some problems, I left only manual synchronization. That is, in order to sync bookmarks again, you need to go to settings / backup and sync / sync with chrome. 

The problem is in a different storage structure (chrome has three root folders, but I have one)

**Comment by Nickfrm** [comment]
Ok, we have an import there, but what about export? I'm gonna provide you an example of what I'm talking about and a case of why it's needed:
- I've created a bookmark from rigami
- Clicked "export" (considering here that there's no auto-sync yet)
- And now I can see those bookmarks in chrome on other devices too

Not sure that it's possible with your current storage structure but just, for now, I see the "bookmarks creation" feature as useless without something like that. 

Hope you'll find a way to create an auto-sync in both directions.

**Comment by danilkinkin** [comment]
If I use standard chrome bookmarks for storage, then I will not be able to store icons, because I generate them myself. 

I have another option for storing this information (chrome.storage.sync), I'm currently experimenting with it. But if I use this, then the synchronization will only be in chrome. But I had plans to make this extension for other browsers and just as a website. Most likely I will have to store data on the server, but I'm not sure about security

**Comment by danilkinkin** [comment]
Will be done in rigami 2.0 milestone https://github.com/orgs/rigami/projects/5/views/1
